import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://cerlwecimducmrwlysqg.supabase.co';
const SUPABASE_SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlcmx3ZWNpbWR1Y21yd2x5c3FnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTgwNjQ2NSwiZXhwIjoyMDk1MzgyNDY1fQ.uosZKA7GaTIZiRcnOxlAzsfjrc-Jd7_wMsLm_2rJ6C8';

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

const list = [
  { nome: 'Marmitex', preco: 27.00 },
  { nome: 'Lá Minuta tradicional', preco: 43.00 },
  { nome: 'Bifes de Coxão Mole Precoce', preco: 14.00 },
  { nome: 'Chuleta de Contrafilé', preco: 14.00 },
  { nome: 'Filé de Frango à Parmegiana', preco: 12.00 },
  { nome: 'Frango Grelhado', preco: 13.00 },
  { nome: 'Bife de Lentilha', preco: 12.00 },
  { nome: 'Arroz Branco', preco: 16.00 },
  { nome: 'Feijão', preco: 16.00 },
  { nome: 'Farofinha Caseira', preco: 10.00 },
  { nome: 'Espaguete', preco: 22.00 },
  { nome: 'Batata Frita', preco: 25.00 },
  { nome: 'Polentinha Frita', preco: 25.00 },
  { nome: 'Ovo Frito', preco: 5.00 },
  { nome: 'Saladas', preco: 12.00 },
  { nome: 'Porção 400g Batata Frita', preco: 20.00 },
  { nome: 'Porção 400g Polentinha Frita', preco: 20.00 },
  { nome: 'Pastel de Frango P', preco: 15.00 },
  { nome: 'Pastel de Frango M', preco: 20.00 },
  { nome: 'Pastel de Frango G', preco: 27.00 },
  { nome: 'Pastel de Frango S', preco: 38.00 },
  { nome: 'Pastel de Frango com Catupiry P', preco: 17.00 },
  { nome: 'Pastel de Frango com Catupiry M', preco: 24.00 },
  { nome: 'Pastel de Frango com Catupiry G', preco: 39.00 },
  { nome: 'Pastel de Frango com Catupiry S', preco: 44.00 },
  { nome: 'Pastel de Frango com Queijo P', preco: 17.00 },
  { nome: 'Pastel de Frango com Queijo M', preco: 44.00 },
  { nome: 'Pastel de Frango com Queijo G', preco: 31.00 },
  { nome: 'Pastel de Frango com Queijo S', preco: 39.00 },
  { nome: 'Pastel de Frango Palmito Queijo P', preco: 19.00 },
  { nome: 'Pastel de Frango Palmito Queijo M', preco: 29.00 },
  { nome: 'Pastel de Frango Palmito Queijo G', preco: 42.00 },
  { nome: 'Pastel de Frango Palmito Queijo S', preco: 48.00 },
  { nome: 'Pastel de Frango com Cheddar P', preco: 17.00 },
  { nome: 'Pastel de Frango com Cheddar M', preco: 24.00 },
  { nome: 'Pastel de Frango com Cheddar G', preco: 39.00 },
  { nome: 'Pastel de Frango com Cheddar S', preco: 44.00 },
  { nome: 'Pastel de Carne P', preco: 11.00 },
  { nome: 'Pastel de Carne M', preco: 16.50 },
  { nome: 'Pastel de Carne G', preco: 25.00 },
  { nome: 'Pastel de Carne S', preco: 35.00 },
  { nome: 'Pastel de Carne com Ovo P', preco: 15.00 },
  { nome: 'Pastel de Carne com Ovo M', preco: 17.00 },
  { nome: 'Pastel de Carne com Ovo G', preco: 29.00 },
  { nome: 'Pastel de Carne com Ovo S', preco: 38.00 },
  { nome: 'Pastel de Carne com Queijo P', preco: 17.00 },
  { nome: 'Pastel de Carne com Queijo M', preco: 24.00 },
  { nome: 'Pastel de Carne com Queijo G', preco: 31.00 },
  { nome: 'Pastel de Carne com Queijo S', preco: 34.00 },
  { nome: 'Pastel de Carne com Catupiry P', preco: 17.00 },
  { nome: 'Pastel de Carne com Catupiry M', preco: 24.00 },
  { nome: 'Pastel de Carne com Catupiry G', preco: 31.00 },
  { nome: 'Pastel de Carne com Catupiry S', preco: 34.00 },
  { nome: 'Pastel de Carne com Cheddar P', preco: 17.00 },
  { nome: 'Pastel de Carne com Cheddar M', preco: 24.00 },
  { nome: 'Pastel de Carne com Cheddar G', preco: 39.00 },
  { nome: 'Pastel de Carne com Cheddar S', preco: 44.00 },
  { nome: 'Pastel de Presunto e Queijo P', preco: 17.00 },
  { nome: 'Pastel de Presunto e Queijo M', preco: 23.00 },
  { nome: 'Pastel de Presunto e Queijo G', preco: 27.00 },
  { nome: 'Pastel de Presunto e Queijo S', preco: 28.00 },
  { nome: 'Pastel Presunto Queijo Ovo P', preco: 17.00 },
  { nome: 'Pastel Presunto Queijo Ovo M', preco: 22.00 },
  { nome: 'Pastel Presunto Queijo Ovo G', preco: 30.00 },
  { nome: 'Pastel Presunto Queijo Ovo S', preco: 33.00 },
  { nome: 'Pastel Presunto Queijo Tomate P', preco: 20.00 },
  { nome: 'Pastel Presunto Queijo Tomate M', preco: 26.00 },
  { nome: 'Pastel Presunto Queijo Tomate G', preco: 34.00 },
  { nome: 'Pastel Presunto Queijo Tomate S', preco: 40.00 },
  { nome: 'Pastel Chocolate Preto P', preco: 18.00 },
  { nome: 'Pastel Chocolate Preto M', preco: 24.00 },
  { nome: 'Pastel Chocolate Branco P', preco: 18.00 },
  { nome: 'Pastel Chocolate Branco M', preco: 24.00 },
  { nome: 'Pastel Chocolate Preto e Branco P', preco: 20.00 },
  { nome: 'Pastel Chocolate Preto e Branco M', preco: 26.00 },
  { nome: 'Pastel Chocolate Preto e Morango P', preco: 20.00 },
  { nome: 'Pastel Chocolate Preto e Morango M', preco: 26.00 },
  { nome: 'Pastel Chocolate Branco e Morango P', preco: 20.00 },
  { nome: 'Pastel Chocolate Branco e Morango M', preco: 26.00 },
  { nome: 'Pastel Chocolate Preto Branco Morango P', preco: 24.00 },
  { nome: 'Pastel Chocolate Preto Branco Morango M', preco: 28.00 },
  { nome: 'Pastel Costela P', preco: 20.00 },
  { nome: 'Pastel Costela M', preco: 29.00 },
  { nome: 'Pastel Costela G', preco: 39.00 },
  { nome: 'Pastel Costela S', preco: 44.00 },
  { nome: 'Pastel Costela com Queijo P', preco: 24.05 },
  { nome: 'Pastel Costela com Queijo M', preco: 29.00 },
  { nome: 'Pastel Costela com Queijo G', preco: 39.00 },
  { nome: 'Pastel Costela com Queijo S', preco: 44.00 },
  { nome: 'Pastel Calabresa com Queijo P', preco: 17.00 },
  { nome: 'Pastel Calabresa com Queijo M', preco: 22.00 },
  { nome: 'Pastel Calabresa com Queijo G', preco: 33.00 },
  { nome: 'Pastel Calabresa com Queijo S', preco: 39.00 },
  { nome: 'Pastel Calabresa Queijo Ovo P', preco: 20.00 },
  { nome: 'Pastel Calabresa Queijo Ovo M', preco: 26.00 },
  { nome: 'Pastel Calabresa Queijo Ovo G', preco: 37.00 },
  { nome: 'Pastel Calabresa Queijo Ovo S', preco: 42.00 },
  { nome: 'Pastel Vegetariano Queijo P', preco: 17.00 },
  { nome: 'Pastel Vegetariano Queijo M', preco: 22.00 },
  { nome: 'Pastel Vegetariano Queijo G', preco: 29.00 },
  { nome: 'Pastel Vegetariano Queijo S', preco: 37.00 },
  { nome: 'Pastel Vegetariano Queijo Ovo Brócolis P', preco: 22.00 },
  { nome: 'Pastel Vegetariano Queijo Ovo Brócolis M', preco: 28.00 },
  { nome: 'Pastel Vegetariano Queijo Ovo Brócolis G', preco: 34.00 },
  { nome: 'Pastel Vegetariano Queijo Ovo Brócolis S', preco: 40.00 },
  { nome: 'Cheese Burguer', preco: 24.00 },
  { nome: 'Cheese Salada', preco: 26.00 },
  { nome: 'Cheese Egg', preco: 28.00 },
  { nome: 'Cheese Bacon', preco: 30.00 },
  { nome: 'Cheese Calabresa', preco: 30.00 },
  { nome: 'Cheese Frango', preco: 28.00 },
  { nome: 'Cheese Armazém', preco: 49.00 },
  { nome: 'X Vegetariano', preco: 28.00 },
  { nome: 'X Egg Vegetariano', preco: 27.00 },
  { nome: 'Misto Presunto Queijo', preco: 8.00 },
  { nome: 'Misto Presunto Queijo Tomate', preco: 15.00 },
  { nome: 'Misto Presunto Queijo Tomate Ovo', preco: 20.00 },
  { nome: 'Misto Salame Queijo', preco: 10.00 },
  { nome: 'Misto Salame Queijo Tomate', preco: 16.00 },
  { nome: 'Misto Salame Queijo Tomate Ovo', preco: 22.00 },
  { nome: 'Água sem Gás Puris', preco: 3.00 },
  { nome: 'Água com Gás Puris', preco: 3.00 },
  { nome: 'Coca-Cola Lata', preco: 6.00 },
  { nome: 'Coca-Cola Zero Lata', preco: 6.00 },
  { nome: 'Coca-Cola 2 Litros', preco: 17.00 },
  { nome: 'Coca-Cola Zero 2 Litros', preco: 17.00 },
  { nome: 'Laranjinha 2 Litros', preco: 15.00 },
  { nome: 'Pureza Guaraná 2 Litros', preco: 15.00 },
  { nome: 'Budweiser 330ml', preco: 10.00 },
  { nome: 'Heineken 330ml', preco: 10.00 },
  { nome: 'Suco de Laranja 500ml', preco: 12.00 },
  { nome: 'Suco de Limão 500ml', preco: 12.00 },
  { nome: 'Suco de Maracujá 500ml', preco: 14.00 },
  { nome: 'Coca-Cola 600ml', preco: 12.00 },
  { nome: 'Laranjinha 600ml', preco: 12.00 },
  { nome: 'Pureza Guaraná 600ml', preco: 12.00 },
  { nome: 'Suco Integral de Uva', preco: 10.00 },
  { nome: 'Pureza 1 Litro', preco: 15.00 },
  { nome: 'Laranjinha 1 Litro', preco: 15.00 },
  { nome: 'Croquete', preco: 8.00 },
  { nome: 'Salsicha Simples', preco: 6.00 },
  { nome: 'Salsicha com Catupiry e Queijo', preco: 8.00 },
  { nome: 'Salsicha Empanada', preco: 9.00 },
  { nome: 'Empada de Frango', preco: 9.00 },
  { nome: 'Assado de Carne', preco: 10.00 },
  { nome: 'Assado de Frango', preco: 10.00 },
  { nome: 'Assado de Presunto e Queijo', preco: 10.00 },
  { nome: 'Risoles de Frango', preco: 9.00 },
  { nome: 'Coxinha de Frango com Catupiry', preco: 9.00 },
  { nome: 'Bolinho de Carne', preco: 12.00 },
  { nome: 'Mini Pastel de Carne', preco: 3.00 },
  { nome: 'Pão de Queijo', preco: 4.00 },
  { nome: 'Prestígio Preto', preco: 2.50 },
  { nome: 'Prestígio Branco', preco: 2.50 },
  { nome: 'Bis Extra', preco: 3.50 },
  { nome: 'Bis Oreo', preco: 3.50 },
  { nome: 'Lacta Branco', preco: 3.50 },
  { nome: 'Lacta ao Leite', preco: 3.50 },
  { nome: 'Diamante Negro', preco: 3.50 },
  { nome: 'Lacta Shot', preco: 3.50 },
  { nome: 'Trento Avelã', preco: 2.50 },
  { nome: 'Trento Chocolate', preco: 2.50 },
  { nome: 'Trento Dark 55%', preco: 2.50 },
  { nome: 'Trento Branco Dark', preco: 2.50 },
  { nome: 'Trento Alegro Preto', preco: 3.50 },
  { nome: 'Trento Alegro Branco', preco: 3.50 },
  { nome: 'Sonho de Valsa', preco: 2.00 },
  { nome: 'Ouro Branco', preco: 2.00 },
  { nome: 'Pé de Moça', preco: 3.00 },
  { nome: 'Paçoquinha Tradicional', preco: 1.00 },
  { nome: 'Gibi', preco: 1.00 },
  { nome: 'Geléia de Frutas', preco: 1.00 },
  { nome: 'Halls Extra Forte', preco: 2.50 },
  { nome: 'Halls Menta', preco: 2.50 },
  { nome: 'Halls Cereja', preco: 2.50 },
  { nome: 'Halls Morango', preco: 2.50 },
  { nome: 'Halls Uva Verde', preco: 2.50 },
  { nome: 'Trident Hortelã', preco: 2.50 },
  { nome: 'Trident Menta', preco: 2.50 },
  { nome: 'Trident Melancia', preco: 2.50 },
  { nome: 'Trident Tutti Frutti', preco: 2.50 },
  { nome: 'Trident Morango', preco: 2.50 },
  { nome: 'Trident Canela', preco: 2.50 }
];

async function seed() {
  try {
    console.log('Clearing old products in "produtos"...');
    const { error: dErr } = await supabase.from('produtos').delete().neq('id', 0);
    if (dErr) {
      console.error('Error clearing products (continuing):', dErr);
    }

    console.log(`Inserting ${list.length} products to Supabase...`);
    // Insert in batches of 50 to avoid any limits
    for (let i = 0; i < list.length; i += 50) {
      const batch = list.slice(i, i + 50);
      const { data, error } = await supabase.from('produtos').insert(batch).select();
      if (error) {
        console.error(`Error inserting batch starting at ${i}:`, error);
      } else {
        console.log(`Inserted batch ${i} to ${i + batch.length} successfully.`);
      }
    }
    console.log('Seeding fully finished!');
  } catch (err) {
    console.error('Unexpected error seeding:', err);
  }
}

seed();
